CREATE DATABASE CURSOR;
USE CURSOR;

CREATE TABLE VENDEDORES(
    IDVENDEDORES INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    JAN INT,
    FEV INT,
    MAR INT
);

INSERT INTO VENDEDORES VALUES(NULL, 'Matheus', 1000, 29831, 3289382);
INSERT INTO VENDEDORES VALUES(NULL, 'Jorje', 1300, 212831, 3400);
INSERT INTO VENDEDORES VALUES(NULL, 'Lucas', 122300, 29831231, 20321);
INSERT INTO VENDEDORES VALUES(NULL, 'Joana', 3212, 231, 1239128);
INSERT INTO VENDEDORES VALUES(NULL, 'Celia', 1000, 12831, 18237);

SELECT NOME, JAN, FEV, MAR, (JAN + FEV + MAR) AS "VALOR TOTAL", (JAN + FEV + MAR) / 3 AS "VALOR MEDIA"
FROM VENDEDORES;


CREATE TABLE VENDAS_TOTAL(
    IDVENDEDORES INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    JAN INT ,
    FEV INT,
    MAR INT,
    VENDA_TOTAL INT,    
    MEDIA INT
);
DELIMITER $
CREATE PROCEDURE INSERINDODADOS()
BEGIN
    DECLARE FIM INT DEFAULT 0;
    DECLARE VAR1, VAR2, VAR3, VARTOTAL, VARMEDIA INT;
    DECLARE VNOME VARCHAR(30);

    DECLARE REG CURSOR FOR (
        SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
    );

    DECLARE CONTINUE HANDLE FOR NOT FOUND SET FIM = 1;

    OPEN REG;

    REPEAT

        FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
        IF NOT FIM THEN 

            SET VARTOTAL = VAR1 + VAR2 + VAR3;
            SET VARMEDIA = VARTOTAL / 3;
            INSERT INTO VENDAS_TOTAL VALUES(NULL, VNOME, VAR1, VAR2, VAR3, VARTOTAL, VARMEDIA);
        END IF;
    UNTIL FIM END REPEAT;

    CLOSE REG;
END;
$

DELIMITER ;